In [1]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

/Users/apple/Downloads/Maven - End-to-End AI Engineering Bootcamp 2026-2/my-codes/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:

import pandas as pd
import openai

In [3]:
df_items = pd.read_json("../../data/meta_Digital_Music_2022_2023_with_category_rating_100_sample_1000.jsonl", lines=True)

In [4]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Digital Music,Fastway,4.7,754,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Fastway,[],"{'Date First Available': 'April 13, 2020'}",B0872KL2TZ,NaN
1,Digital Music,Awaken Your Heart From Its Ancient Sleep (Musi...,4.8,574,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Madonna Format: Audio CD,[],{'Package Dimensions': '5.55 x 4.97 x 0.54 inc...,B008A0PUSY,NaN
2,Digital Music,Grimes: Art Angels Vinyl LP,4.8,1200,[],[2015 album from Grimes on vinyl. Comes with d...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Grimes Format: Unknown Binding,[],{'Package Dimensions': '12.4 x 12.2 x 0.4 inch...,B01974S2ZE,NaN
3,Digital Music,Aja [Vinyl LP],4.8,3756,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Steely Dan,[],{'Package Dimensions': '15.39 x 13.19 x 0.79 i...,B00U1OCGGG,NaN
4,Digital Music,It's Not Big It's Large by Lyle Lovett (2007) ...,4.4,130,[],[],41.88,[{'thumb': 'https://m.media-amazon.com/images/...,[],Lyle Lovett Format: Audio CD,[],"{'Date First Available': 'July 28, 2014'}",B00G2IJ4IS,NaN

In [5]:
list(df_items["features"].items())[0]

(0, [])

In [6]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/51Z+tjiMfBL._SS40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51Z+tjiMfBL.jpg',
   'variant': 'MAIN',
   'hi_res': None}])

### Preprocess title and features

In [15]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [10]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [16]:
df_items["description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [17]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,image
0,Digital Music,Fastway,4.7,754,[],Fastway,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Fastway,[],"{'Date First Available': 'April 13, 2020'}",B0872KL2TZ,NaN,https://m.media-amazon.com/images/I/51Z+tjiMfB...
1,Digital Music,Awaken Your Heart From Its Ancient Sleep (Musi...,4.8,574,[],Awaken Your Heart From Its Ancient Sleep (Musi...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Madonna Format: Audio CD,[],{'Package Dimensions': '5.55 x 4.97 x 0.54 inc...,B008A0PUSY,NaN,https://m.media-amazon.com/images/I/51sPlcA9mQ...
2,Digital Music,Grimes: Art Angels Vinyl LP,4.8,1200,[],Grimes: Art Angels Vinyl LP,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Grimes Format: Unknown Binding,[],{'Package Dimensions': '12.4 x 12.2 x 0.4 inch...,B01974S2ZE,NaN,https://m.media-amazon.com/images/I/513XxFczpM...
3,Digital Music,Aja [Vinyl LP],4.8,3756,[],Aja [Vinyl LP],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Steely Dan,[],{'Package Dimensions': '15.39 x 13.19 x 0.79 i...,B00U1OCGGG,NaN,https://m.media-amazon.com/images/I/41DqKB567m...
4,Digital Music,It's Not Big It's Large by Lyle Lovett (2007) ...,4.4,130,[],It's Not Big It's Large by Lyle Lovett (2007) ...,41.88,[{'thumb': 'https://m.media-amazon.com/images/...,[],Lyle Lovett Format: Audio CD,[],"{'Date First Available': 'July 28, 2014'}",B00G2IJ4IS,NaN,https://m.media-amazon.com/images/I/61KvKLn0Ax...

In [ ]:
# Get sample
list(df_items["description"].items())[0]

##### Sample 50 items from dataset

In [18]:
df_sample = df_items.sample(50, random_state=42)

In [19]:
len(df_sample)

50

In [20]:
data_to_embed = df_sample[["description", "image", "rating_number", "price", "average_rating", "parent_asin"]].to_dict(orient="records")

In [21]:
data_to_embed

[{'description': "By John O'Donohue Beauty: The Invisible Embrace Audio CD - March 2004 ",
  'image': 'https://m.media-amazon.com/images/I/31QDhYrrgnL.jpg',
  'rating_number': 496,
  'price': 12.0,
  'average_rating': 4.8,
  'parent_asin': 'B01726HQVK'},
 {'description': '5 Classic Albums ',
  'image': 'https://m.media-amazon.com/images/I/51dpJ3j1kWL.jpg',
  'rating_number': 642,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B07DMPR78Q'},
 {'description': 'Unplugged (CD) ',
  'image': 'https://m.media-amazon.com/images/I/411b8YKbYBL.jpg',
  'rating_number': 3068,
  'price': 16.99,
  'average_rating': 4.8,
  'parent_asin': 'B08VQYCNHB'},
 {'description': 'Elvis Presley - He Touched Me The Gospel Music - 3pc set ',
  'image': 'https://m.media-amazon.com/images/I/5149Y9AH32L.jpg',
  'rating_number': 749,
  'price': 14.71,
  'average_rating': 4.7,
  'parent_asin': '5559166928'},
 {'description': 'GOT7 MAD 4th Mini Album Vertical Version White CD+PhotoCard+Booklet+Tracking Sealed JYP ',
  'image': 'https://m.media-amazon.com/images/I/51e-5U2lCdL.jpg',
  'rating_number': 108,
  'price': 21.99,
  'average_rating': 4.6,
  'parent_asin': 'B01BNEZQB4'},
 {'description': 'Be Thankful For What You Got ',
  'image': 'https://m.media-amazon.com/images/I/511On8Mb5HL.jpg',
  'rating_number': 133,
  'price': nan,
  'average_rating': 4.5,
  'parent_asin': 'B0052OM6GA'},
 {'description': 'Chet ',
  'image': 'https://m.media-amazon.com/images/I/41CVgXa11+L.jpg',
  'rating_number': 311,
  'price': 3.59,
  'average_rating': 4.4,
  'parent_asin': 'B001CYKKSU'},
 {'description': 'Enrique Iglesias- Sex and Love Deluxe Extended Edition with 4 Bonus Tracks ',
  'image': 'https://m.media-amazon.com/images/I/51grTONtjpL.jpg',
  'rating_number': 742,
  'price': 2.99,
  'average_rating': 4.6,
  'parent_asin': 'B00J3J3KNI'},
 {'description': 'Ratt & Roll 8191 by Ratt (1991) Audio CD ',
  'image': 'https://m.media-amazon.com/images/I/51L+vAuGSAL.jpg',
  'rating_number': 387,
  'price': 28.95,
  'average_rating': 4.8,
  'parent_asin': 'B00FY3DD84'},
 {'description': 'Best Of Dire Straits & Mark Knopfler: Private Investigations (2CD) by Dire Straits, Mark Knopfler (2005) Audio CD ',
  'image': 'https://m.media-amazon.com/images/I/51wxgNhGzbL.jpg',
  'rating_number': 1932,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B00G2JF3E6'},
 {'description': 'GORDON LIGHTFOOT - endless wire WB 3149 (LP vinyl record) ',
  'image': 'https://m.media-amazon.com/images/I/41Os-5z-GdL.jpg',
  'rating_number': 136,
  'price': 190.0,
  'average_rating': 4.7,
  'parent_asin': 'B003XX6ZIM'},
 {'description': 'Lit - A Place in the Sun ',
  'image': 'https://m.media-amazon.com/images/I/41tGuOyEw9L.jpg',
  'rating_number': 441,
  'price': 29.06,
  'average_rating': 4.6,
  'parent_asin': 'B003D0L2XS'},
 {'description': '90125 (expanded & remastered) ',
  'image': 'https://m.media-amazon.com/images/I/21RAAXGZHCL.jpg',
  'rating_number': 1333,
  'price': 28.61,
  'average_rating': 4.7,
  'parent_asin': 'B000228V66'},
 {'description': 'Chain: Johnny Version ',
  'image': 'https://m.media-amazon.com/images/I/61gWmG-Y5TL.jpg',
  'rating_number': 117,
  'price': nan,
  'average_rating': 4.4,
  'parent_asin': 'B07BRVGN5G'},
 {'description': 'Born To Run: 30th Anniversary Edition [2 DVD + 1 CD] By Bruce Springsteen (2005-11-12) ',
  'image': 'https://m.media-amazon.com/images/I/51IB2dR+iiL.jpg',
  'rating_number': 2781,
  'price': 46.98,
  'average_rating': 4.8,
  'parent_asin': 'B014I6M5KE'},
 {'description': 'AT THE CARNEG ',
  'image': 'https://m.media-amazon.com/images/I/31h9vnD4pCL.jpg',
  'rating_number': 226,
  'price': 123.47,
  'average_rating': 4.6,
  'parent_asin': 'B000024WET'},
 {'description': "Handel's Messiah: A Soulful Celebration by unknown (1992) Audio CD ",
  'image': 'https://m.media-amazon.com/images/I/61v8QyChPOL.jpg',
  'rating_number': 455,
  'price': 48.98,
  'average_rating': 4.8,
  'parent_asin': 'B00G2J0CH4'},
 {'description': 'Goetterdaemmerung ',
  'image': 'https://m.media-amazon.com/images/I/51OZBcv0X0L.jpg',
  'rating_number': 161,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B00000ATXG'},
 {'description': 'Breath of the Heart ',
  'image': 'https://m.media-amazon.com/images/I/41VQ3B4QQFL.jpg',
  'rating_number': 122,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B00005JIZW'},
 {'description': 'Vixen: Rev It Up! ',
  'image': 'https://m.media-amazon.com/images/I/51zEjhkM2kL.jpg',
  'rating_number': 256,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B00BMU4YW2'},
 {'description': 'Wings At the Speed of Sound ',
  'image': 'https://m.media-amazon.com/images/I/51Y88aSiT3L.jpg',
  'rating_number': 247,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B000JFHKXG'},
 {'description': 'Christmas After Midnight ',
  'image': 'https://m.media-amazon.com/images/I/51ooHEDz7BL.jpg',
  'rating_number': 405,
  'price': 10.48,
  'average_rating': 4.8,
  'parent_asin': 'B081BD339D'},
 {'description': 'Seventeen - Face the Sun, Carat Version (The 8 Cover incl. CD, Booklet, Digipak, Lyric Book, Photocard, Extra Photocards) ',
  'image': 'https://m.media-amazon.com/images/I/51DxhKQchWL.jpg',
  'rating_number': 325,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B0B2MYHG7H'},
 {'description': 'Celebration Day (2 CD + 1 DVD, CD sized digipak) CD+DVD Edition by Led Zeppelin (2012) Audio CD ',
  'image': 'https://m.media-amazon.com/images/I/51enYVDQbxL.jpg',
  'rating_number': 5498,
  'price': 87.99,
  'average_rating': 4.7,
  'parent_asin': 'B00FT19510'},
 {'description': 'STRAY KIDS GO生 1st Album LIMITED CD+Photo Book+5 Card+Film+Lyric+PreOrder+TRACKING CODE K-POP SEALED ',
  'image': 'https://m.media-amazon.com/images/I/41N81DmMGLL.jpg',
  'rating_number': 497,
  'price': nan,
  'average_rating': 4.8,
  'parent_asin': 'B089Q4334P'},
 {'description': 'Strength in Unity - MP20-EN247 - Ultra Rare - 1st Edition ',
  'image': 'https://m.media-amazon.com/images/I/51KOYzne3iL.jpg',
  'rating_number': 135,
  'price': 2.43,
  'average_rating': 4.7,
  'parent_asin': 'B08GL48XR2'},
 {'description': 'TOM PETTY-DAMN THE TORPEDOES ',
  'image': 'https://m.media-amazon.com/images/I/51WbWzLWNlL._AC_.jpg',
  'rating_number': 1444,
  'price': 39.99,
  'average_rating': 4.8,
  'parent_asin': 'B003X8JTT4'},
 {'description': 'BEE GEES ODESSA MINI LP CD OBI ',
  'image': 'https://m.media-amazon.com/images/I/41MIPtAc5ML.jpg',
  'rating_number': 287,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B00NF15R2W'},
 {'description': 'Flourishing Incl. 76pg Booklet, Postcard + Photocard ',
  'image': 'https://m.media-amazon.com/images/I/412b77mtimL.jpg',
  'rating_number': 157,
  'price': 17.8,
  'average_rating': 4.8,
  'parent_asin': 'B07T5SDZQY'},
 {'description': 'Withholding Nothing (CD/DVD) by William McDowell (2013-10-21) ',
  'image': 'https://m.media-amazon.com/images/I/512LqfBvG6L.jpg',
  'rating_number': 374,
  'price': 52.71,
  'average_rating': 4.7,
  'parent_asin': 'B01MFE6AF6'},
 {'description': 'Carthage ',
  'image': 'https://m.media-amazon.com/images/I/61QSnAXzOvL.jpg',
  'rating_number': 1216,
  'price': 5.75,
  'average_rating': 3.9,
  'parent_asin': '0385366736'},
 {'description': 'Complete Classic Rock Collection 8 CD Box ',
  'image': 'https://m.media-amazon.com/images/I/316zP7tHdvL.jpg',
  'rating_number': 644,
  'price': nan,
  'average_rating': 4.4,
  'parent_asin': 'B004NW4BL0'},
 {'description': 'The Songs of Distant Earth ',
  'image': 'https://m.media-amazon.com/images/I/51fcXEnGplL.jpg',
  'rating_number': 802,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B00FZ1PCK2'},
 {'description': 'Mr. Misunderstood On The Rocks: Live And Mostly Unplugged ',
  'image': 'https://m.media-amazon.com/images/I/61PhGHDMGTL.jpg',
  'rating_number': 120,
  'price': 7.97,
  'average_rating': 4.8,
  'parent_asin': 'B01LWRURZR'},
 {'description': 'Once Historias Y un Piano ',
  'image': 'https://m.media-amazon.com/images/I/51hpZ+FapIL.jpg',
  'rating_number': 213,
  'price': 17.7,
  'average_rating': 4.7,
  'parent_asin': 'B00GMMOEZW'},
 {'description': 'BTS - Map of the Soul: Persona (CD) ',
  'image': 'https://m.media-amazon.com/images/I/413Ug3S7xpL.jpg',
  'rating_number': 1246,
  'price': 26.47,
  'average_rating': 4.8,
  'parent_asin': 'B07PPJ2NY3'},
 {'description': 'ELTON JOHN Tumbleweed Connection UNI 73096 LP Vinyl GF Booklet ',
  'image': 'https://m.media-amazon.com/images/I/51r0IUZAraL._AC_.jpg',
  'rating_number': 204,
  'price': nan,
  'average_rating': 4.8,
  'parent_asin': 'B01N01TET7'},
 {'description': 'Bon Jovi - Gonna Set The World On Fire: The Legendary Broadcasts 1983-1993 [4 CD Set] ',
  'image': 'https://m.media-amazon.com/images/I/51SYCzL6-SL.jpg',
  'rating_number': 125,
  'price': 18.4,
  'average_rating': 4.4,
  'parent_asin': 'B01MTD4SZ7'},
 {'description': 'Pink Friday [Deluxe Edition] by Nicki Minaj [Music CD] ',
  'image': 'https://m.media-amazon.com/images/I/51V-0W7WwbL.jpg',
  'rating_number': 227,
  'price': 32.98,
  'average_rating': 4.8,
  'parent_asin': 'B00PUUWJ8G'},
 {'description': 'TASHI LAMA TIBETAN MASTER CHANTS ',
  'image': 'https://m.media-amazon.com/images/I/21OOUl7Dw3L.jpg',
  'rating_number': 115,
  'price': 53.56,
  'average_rating': 4.5,
  'parent_asin': 'B0018L8Y3U'},
 {'description': '50 Number Ones ',
  'image': 'https://m.media-amazon.com/images/I/51bLnquUv9L.jpg',
  'rating_number': 4158,
  'price': 13.96,
  'average_rating': 4.8,
  'parent_asin': 'B08L718W4P'},
 {'description': 'IVE ELEVEN 1st Single Album Random Version CD+1p Folding Poster On Pack+92p PhotoBook+1p PhotoCard+Tracking Sealed ',
  'image': 'https://m.media-amazon.com/images/I/31XZeS+ho9L.jpg',
  'rating_number': 161,
  'price': 19.99,
  'average_rating': 4.6,
  'parent_asin': 'B09M8CC81H'},
 {'description': 'ASTRO [ ALL YOURS ] 2nd Album 3 Ver FULL SET. 3 CD+3 Photo Book(each 104p)+3 Accordion Post Card(each 6p) 3 Message Card+3 Photo Card+3 Folded Poster(On pack) K-POP SEALED ',
  'image': 'https://m.media-amazon.com/images/I/41RC4RvcTuL.jpg',
  'rating_number': 191,
  'price': 83.99,
  'average_rating': 4.8,
  'parent_asin': 'B08ZN4GW2F'},
 {'description': 'Doughnut Version A incl. Trading Card ',
  'image': 'https://m.media-amazon.com/images/I/51GMmZXYnEL.jpg',
  'rating_number': 156,
  'price': 28.21,
  'average_rating': 4.6,
  'parent_asin': 'B09HXZ3G6C'},
 {'description': 'Who Are You Picture Disc ',
  'image': 'https://m.media-amazon.com/images/I/51gFzGXQZjL.jpg',
  'rating_number': 822,
  'price': 129.99,
  'average_rating': 4.7,
  'parent_asin': 'B01BCSX2AI'},
 {'description': 'Strangers in the Night by Sinatra, Frank (1990) Audio CD ',
  'image': 'https://m.media-amazon.com/images/I/51Y9u+4-nhL.jpg',
  'rating_number': 287,
  'price': 24.99,
  'average_rating': 4.8,
  'parent_asin': 'B00GG3SOJE'},
 {'description': "SM Entertainment EXO - DON'T MESS UP MY TEMPO [Andante ver.] (Vol.5) CD+Booklet+Photocard+Pre-Order Benefit+Folded Poster+Extra Photocards Set ",
  'image': 'https://m.media-amazon.com/images/I/41pTXKmcQcL.jpg',
  'rating_number': 196,
  'price': 52.5,
  'average_rating': 4.7,
  'parent_asin': 'B07J1C4RXN'},
 {'description': 'Van Lear Rose Vault 24 Edition ',
  'image': 'https://m.media-amazon.com/images/I/61o1jW-12mL.jpg',
  'rating_number': 515,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B010OSUYGW'},
 {'description': '187 by Samuel L. Jackson ',
  'image': 'https://m.media-amazon.com/images/I/41upBywK44L.jpg',
  'rating_number': 307,
  'price': 29.97,
  'average_rating': 4.6,
  'parent_asin': 'B01M9IAW2Z'},
 {'description': 'Burning Lights [Deluxe Tour Edition][CD/DVD Combo] by Chris Tomlin (2012-07-29) ',
  'image': 'https://m.media-amazon.com/images/I/41AC17LzoAL.jpg',
  'rating_number': 556,
  'price': nan,
  'average_rating': 4.8,
  'parent_asin': 'B01JTCLT3Q'}]

#### Define the embedding function

In [22]:
response = openai.embeddings.create(
    input="Random Text",
    model="text-embedding-3-small"
)

In [23]:
len(response.data[0].embedding)

1536

In [24]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [25]:
get_embedding("Hi")

[-0.006954193115234375,
 -0.03533935546875,
 0.0015869140625,
 0.06536865234375,
 0.032928466796875,
 -0.0242156982421875,
 -0.026123046875,
 0.049407958984375,
 0.0162506103515625,
 -0.05169677734375,
 -0.01343536376953125,
 -0.0144805908203125,
 -0.0260009765625,
 -0.0032596588134765625,
 0.02459716796875,
 0.0011425018310546875,
 -0.053497314453125,
 0.01508331298828125,
 0.01148223876953125,
 0.033935546875,
 0.049285888671875,
 0.020355224609375,
 -0.01395416259765625,
 0.01885986328125,
 0.0171661376953125,
 0.0241851806640625,
 0.0182647705078125,
 -0.0012063980102539062,
 0.0196075439453125,
 -0.03680419921875,
 0.027679443359375,
 -0.0282440185546875,
 0.0276641845703125,
 -0.0162200927734375,
 -0.0117645263671875,
 -0.016021728515625,
 -0.0140838623046875,
 0.037567138671875,
 0.0189208984375,
 -0.03765869140625,
 0.04345703125,
 -0.012420654296875,
 0.0209503173828125,
 0.0135040283203125,
 0.0019893646240234375,
 0.00025463104248046875,
 -0.04913330078125,
 0.00832366943359375,
 0.0183868408203125,
 0.0294647216796875,
 -0.0267486572265625,
 0.00762176513671875,
 0.024993896484375,
 0.10650634765625,
 0.036285400390625,
 -0.010284423828125,
 0.059539794921875,
 0.023651123046875,
 -0.004093170166015625,
 0.00013363361358642578,
 -0.0191192626953125,
 0.00971221923828125,
 0.00835418701171875,
 0.004024505615234375,
 -0.007110595703125,
 -0.0135650634765625,
 -0.02392578125,
 0.01214599609375,
 -0.0209503173828125,
 -0.0138702392578125,
 -0.00142669677734375,
 0.0362548828125,
 -0.0286102294921875,
 -0.007221221923828125,
 -0.004337310791015625,
 -0.030120849609375,
 -0.08526611328125,
 -0.037750244140625,
 -0.0012693405151367188,
 0.0097503662109375,
 -0.0274505615234375,
 0.0221405029296875,
 -0.037109375,
 -0.01194000244140625,
 -0.0562744140625,
 -0.006053924560546875,
 -0.08074951171875,
 0.0163726806640625,
 -0.026702880859375,
 -0.00923919677734375,
 -0.01568603515625,
 0.044219970703125,
 -0.028411865234375,
 -0.0235443115234375,
 0.00933837890625,
 0.01165008544921875,
 -0.024749755859375,
 -0.0011453628540039062,
 0.05902099609375,
 -0.00936126708984375,
 0.037872314453125,
 -0.0294036865234375,
 0.0396728515625,
 -0.0104827880859375,
 0.01157379150390625,
 0.039306640625,
 0.00847625732421875,
 -0.011260986328125,
 -0.053131103515625,
 0.0255889892578125,
 -0.06597900390625,
 -0.07818603515625,
 -0.0011310577392578125,
 0.01006317138671875,
 0.00897979736328125,
 0.040496826171875,
 0.01519775390625,
 -0.057342529296875,
 -0.00016546249389648438,
 -0.06658935546875,
 0.00370025634765625,
 -0.0048828125,
 0.0283203125,
 -0.036529541015625,
 -0.06097412109375,
 0.0211334228515625,
 0.0011720657348632812,
 0.0168609619140625,
 -0.04742431640625,
 0.0035858154296875,
 0.0506591796875,
 0.01546478271484375,
 -0.0258026123046875,
 -0.007259368896484375,
 -0.029876708984375,
 0.03668212890625,
 -0.037445068359375,
 0.028289794921875,
 -0.043792724609375,
 -0.0225372314453125,
 0.031219482421875,
 -0.00887298583984375,
 0.005741119384765625,
 -0.0159912109375,
 0.0219879150390625,
 -0.01502227783203125,
 0.001239776611328125,
 0.0670166015625,
 -0.0281219482421875,
 -0.01538848876953125,
 0.027099609375,
 0.0218048095703125,
 -0.05230712890625,
 0.024444580078125,
 0.01270294189453125,
 -0.029510498046875,
 0.0150299072265625,
 -0.029510498046875,
 -0.0239105224609375,
 0.008544921875,
 0.033294677734375,
 0.0160980224609375,
 0.01226806640625,
 -0.0526123046875,
 -0.038970947265625,
 0.01161956787109375,
 0.028350830078125,
 0.0367431640625,
 -0.032806396484375,
 -0.0012140274047851562,
 -0.024871826171875,
 0.0292816162109375,
 -0.0323486328125,
 -0.0079345703125,
 -0.01256561279296875,
 -0.005157470703125,
 0.0093231201171875,
 0.0001804828643798828,
 -0.06842041015625,
 -0.0179901123046875,
 0.0164337158203125,
 0.09735107421875,
 0.0054168701171875,
 0.005706787109375,
 -0.032745361328125,
 -0.0205230712890625,
 -0.01186370849609375,
 0.005298614501953125,
 0.02130126953125,
 0.043304443359375,
 0.0006113052368164062,
 0.061859130859375,
 0.00408172607421875,
 0.0051727294921875,
 -0.0060882568359375,
 -0.0443115234375,
 0.0809326171875,
 -0.007312774658203125,
 -0.005275726318359375,
 -0.0023632049560546875,
 0.0218505859375,
 -0.05535888671875,
 0.0171356201171875,
 -0.01450347900390625,
 -0.0244903564453125,
 -0.0212249755859375,
 0.0222930908203125,
 0.0579833984375,
 -0.00018334388732910156,
 -0.048187255859375,
 0.05255126953125,
 -0.033843994140625,
 0.00704193115234375,
 0.0300750732421875,
 -0.01337432861328125,
 -0.034698486328125,
 0.044952392578125,
 0.0028324127197265625,
 0.050018310546875,
 0.01233673095703125,
 -0.00939178466796875,
 0.0027828216552734375,
 0.062255859375,
 0.034210205078125,
 0.021820068359375,
 0.0178375244140625,
 -0.01308441162109375,
 -0.01313018798828125,
 0.01541900634765625,
 -0.0341796875,
 0.0223541259765625,
 0.049224853515625,
 -0.0477294921875,
 -0.046661376953125,
 0.0200042724609375,
 0.0228271484375,
 0.03033447265625,
 -0.01256561279296875,
 0.0163726806640625,
 -0.0150299072265625,
 -0.0338134765625,
 0.006473541259765625,
 0.0006685256958007812,
 0.027740478515625,
 0.022125244140625,
 -0.0040130615234375,
 0.00859832763671875,
 -0.0650634765625,
 0.01325225830078125,
 0.01546478271484375,
 0.008575439453125,
 0.01056671142578125,
 0.01342010498046875,
 -0.0222015380859375,
 -0.027557373046875,
 0.0258636474609375,
 0.0035915374755859375,
 0.038665771484375,
 -0.024810791015625,
 -0.04058837890625,
 -0.0237274169921875,
 -0.037261962890625,
 -0.00653839111328125,
 -0.044464111328125,
 -0.055908203125,
 -0.04241943359375,
 0.01171112060546875,
 0.031219482421875,
 -0.01395416259765625,
 0.005786895751953125,
 -0.0034809112548828125,
 -0.02642822265625,
 0.035369873046875,
 -0.01007080078125,
 -0.0068511962890625,
 0.0150299072265625,
 0.0205230712890625,
 -0.016510009765625,
 -0.0003383159637451172,
 0.0164337158203125,
 -0.046630859375,
 -0.023651123046875,
 -0.006351470947265625,
 0.035491943359375,
 -0.06854248046875,
 0.0202484130859375,
 -0.00971221923828125,
 -0.034576416015625,
 0.03424072265625,
 0.029541015625,
 0.035888671875,
 0.01049041748046875,
 -0.01104736328125,
 -0.033447265625,
 0.003017425537109375,
 0.0179595947265625,
 -0.0066070556640625,
 -0.0220947265625,
 0.0236968994140625,
 -0.03240966796875,
 0.0714111328125,
 0.0149078369140625,
 0.0093841552734375,
 -0.0008640289306640625,
 -0.008331298828125,
 0.0288238525390625,
 0.00365447998046875,
 -0.03118896484375,
 0.00817108154296875,
 0.0066986083984375,
 -0.035186767578125,
 0.0140838623046875,
 0.03472900390625,
 -0.0280914306640625,
 -0.041015625,
 0.0034160614013671875,
 -0.00045180320739746094,
 -0.01464080810546875,
 0.00241851806640625,
 -0.04412841796875,
 0.006450653076171875,
 -0.04644775390625,
 0.027557373046875,
 -0.01715087890625,
 0.0007128715515136719,
 -0.0209808349609375,
 0.0609130859375,
 0.00864410400390625,
 -0.01812744140625,
 -0.0114898681640625,
 -0.0009918212890625,
 -0.023651123046875,
 0.0037441253662109375,
 -0.007396697998046875,
 0.0191802978515625,
 0.00792694091796875,
 -0.0430908203125,
 0.0235748291015625,
 -0.052215576171875,
 0.0509033203125,
 -0.0247955322265625,
 -0.050048828125,
 -0.058319091796875,
 0.01065826416015625,
 0.006870269775390625,
 -0.0106658935546875,
 0.00433349609375,
 -0.0106201171875,
 -0.0173492431640625,
 -0.0088043212890625,
 0.036590576171875,
 0.036956787109375,
 -0.0159912109375,
 -0.02587890625,
 -0.02069091796875,
 -0.03619384765625,
 0.071044921875,
 -0.002899169921875,
 -0.01165771484375,
 0.05010986328125,
 -0.056549072265625,
 0.0002474784851074219,
 0.0009765625,
 -0.03662109375,
 0.053558349609375,
 0.032073974609375,
 -0.06048583984375,
 0.004283905029296875,
 0.0207366943359375,
 0.051025390625,
 -0.01318359375,
 0.01358795166015625,
 0.0013637542724609375,
 0.0117950439453125,
 -0.04095458984375,
 0.0231170654296875,
 0.03863525390625,
 -0.00536346435546875,
 0.01149749755859375,
 -0.0015935897827148438,
 0.0195159912109375,
 0.0506591796875,
 0.0175628662109375,
 -0.028564453125,
 0.05731201171875,
 -0.007396697998046875,
 0.025054931640625,
 -0.038787841796875,
 -0.0308990478515625,
 0.015869140625,
 0.07806396484375,
 0.0032253265380859375,
 0.042449951171875,
 -0.0235595703125,
 0.01837158203125,
 -0.0203399658203125,
 0.036102294921875,
 0.0227203369140625,
 -0.00960540771484375,
 -0.01220703125,
 0.02191162109375,
 -0.060302734375,
 0.0103912353515625,
 0.0091705322265625,
 -0.01244354248046875,
 -0.0193328857421875,
 -0.04937744140625,
 0.01158905029296875,
 0.020263671875,
 -0.016021728515625,
 0.0155029296875,
 -0.04864501953125,
 0.056976318359375,
 0.022705078125,
 0.02703857421875,
 -0.028289794921875,
 -0.0132293701171875,
 -0.00849151611328125,
 0.0151214599609375,
 0.0095672607421875,
 0.01218414306640625,
 0.00016498565673828125,
 -0.0198211669921875,
 0.0255584716796875,
 -0.01727294921875,
 0.046478271484375,
 0.04315185546875,
 -0.06390380859375,
 0.01387786865234375,
 -0.07275390625,
 -0.0229949951171875,
 0.011260986328125,
 -0.01212310791015625,
 0.040496826171875,
 -0.040374755859375,
 -0.0128326416015625,
 0.006866455078125,
 0.038726806640625,
 0.0238189697265625,
 0.0236358642578125,
 -0.00591278076171875,
 -0.0078277587890625,
 -0.00844573974609375,
 -0.03973388671875,
 -0.01006317138671875,
 -0.044219970703125,
 -0.003932952880859375,
 -0.00711822509765625,
 -0.022857666015625,
 -0.0186614990234375,
 -0.0148773193359375,
 -0.002674102783203125,
 0.0080108642578125,
 0.00360107421875,
 0.006786346435546875,
 0.02197265625,
 0.01087188720703125,
 -0.009979248046875,
 0.0027313232421875,
 -0.029388427734375,
 0.0247344970703125,
 -0.0003249645233154297,
 0.04766845703125,
 0.0355224609375,
 0.0236053466796875,
 -0.034759521484375,
 0.0022106170654296875,
 -0.007663726806640625,
 -0.0221710205078125,
 -0.0758056640625,
 0.0294342041015625,
 0.0118560791015625,
 0.04754638671875,
 -0.00933074951171875,
 -0.01491546630859375,
 -0.039947509765625,
 0.002056121826171875,
 -0.01995849609375,
 0.006038665771484375,
 -0.015167236328125,
 0.004207611083984375,
 -0.006122589111328125,
 -0.034271240234375,
 0.066162109375,
 -0.01026153564453125,
 0.0723876953125,
 0.0244293212890625,
 0.02105712890625,
 -0.044036865234375,
 -0.035003662109375,
 0.0196685791015625,
 0.01983642578125,
 0.0870361328125,
 -0.0184173583984375,
 -0.0291290283203125,
 -0.0157623291015625,
 0.0019683837890625,
 -0.0030689239501953125,
 -0.04052734375,
 -0.051422119140625,
 -0.01534271240234375,
 0.00829315185546875,
 -0.0081787109375,
 0.051727294921875,
 0.04180908203125,
 -0.038848876953125,
 -0.032501220703125,
 0.01256561279296875,
 -0.01227569580078125,
 -0.0150146484375,
 0.0067901611328125,
 0.04522705078125,
 -0.01256561279296875,
 -0.056427001953125,
 -0.024688720703125,
 -0.0036067962646484375,
 -0.001644134521484375,
 -0.006252288818359375,
 0.02447509765625,
 -0.034149169921875,
 0.025634765625,
 0.00678253173828125,
 -0.025421142578125,
 -0.006855010986328125,
 0.005031585693359375,
 -0.016448974609375,
 -0.011474609375,
 -0.031280517578125,
 -0.005279541015625,
 0.00202178955078125,
 0.038848876953125,
 -0.017425537109375,
 -0.032470703125,
 0.0056915283203125,
 -0.0287322998046875,
 0.00962066650390625,
 -0.005336761474609375,
 -0.044403076171875,
 0.0004024505615234375,
 -0.02874755859375,
 0.03436279296875,
 0.006206512451171875,
 0.01303863525390625,
 0.0117034912109375,
 -0.0020599365234375,
 0.0249176025390625,
 0.0330810546875,
 -0.00566864013671875,
 0.041351318359375,
 0.041839599609375,
 -0.0196990966796875,
 -0.0309600830078125,
 0.044403076171875,
 -0.01018524169921875,
 0.02099609375,
 -0.0184783935546875,
 -0.0252227783203125,
 -0.004535675048828125,
 0.0099334716796875,
 0.0195159912109375,
 0.004276275634765625,
 -0.00250244140625,
 0.01358795166015625,
 0.007259368896484375,
 0.0006437301635742188,
 0.03411865234375,
 -0.009368896484375,
 -0.0281982421875,
 0.005802154541015625,
 -0.02349853515625,
 -0.0161895751953125,
 -0.0087738037109375,
 -0.0289154052734375,
 -0.011444091796875,
 0.0086212158203125,
 -0.0152587890625,
 -0.0034809112548828125,
 0.0103759765625,
 0.035552978515625,
 0.009765625,
 -0.024383544921875,
 -0.02239990234375,
 -0.00887298583984375,
 -0.033172607421875,
 -0.0235748291015625,
 0.0013675689697265625,
 -0.0107421875,
 0.0280303955078125,
 0.029571533203125,
 0.0305633544921875,
 0.0169219970703125,
 -2.562999725341797e-05,
 -0.0017423629760742188,
 0.027252197265625,
 0.01158905029296875,
 -0.004146575927734375,
 -0.0214080810546875,
 -0.045745849609375,
 -0.03424072265625,
 0.004215240478515625,
 0.0018758773803710938,
 -0.01544952392578125,
 -0.0013532638549804688,
 -0.06658935546875,
 0.01267242431640625,
 -0.0037403106689453125,
 0.0025806427001953125,
 0.0223541259765625,
 -0.016876220703125,
 -0.023895263671875,
 -0.0008182525634765625,
 0.0408935546875,
 0.011505126953125,
 -0.041290283203125,
 -0.033050537109375,
 0.02301025390625,
 -0.001796722412109375,
 0.02685546875,
 0.016326904296875,
 -0.0128326416015625,
 -0.01544952392578125,
 -0.0355224609375,
 0.007312774658203125,
 0.03778076171875,
 0.039642333984375,
 0.0211944580078125,
 -0.0230712890625,
 -0.026092529296875,
 -0.035003662109375,
 0.002056121826171875,
 0.01983642578125,
 0.0243988037109375,
 0.023956298828125,
 -0.013671875,
 -0.0272369384765625,
 -0.0032806396484375,
 -0.006744384765625,
 -0.0101776123046875,
 0.016082763671875,
 -0.039306640625,
 0.01056671142578125,
 -0.003307342529296875,
 0.0163421630859375,
 -0.0008912086486816406,
 0.03411865234375,
 -0.00025534629821777344,
 0.005283355712890625,
 0.01441192626953125,
 0.01116180419921875,
 -0.0189361572265625,
 0.0025424957275390625,
 -0.044403076171875,
 -0.00469970703125,
 -0.016143798828125,
 -0.0034198760986328125,
 -0.003108978271484375,
 -0.040252685546875,
 -0.006084442138671875,
 -0.01239013671875,
 0.00566864013671875,
 0.0095672607421875,
 -0.0092315673828125,
 -0.0173492431640625,
 -0.0187835693359375,
 -0.01100921630859375,
 0.00913238525390625,
 0.0131072998046875,
 0.00479888916015625,
 -0.01494598388671875,
 -0.021087646484375,
 0.01349639892578125,
 0.0021820068359375,
 0.03692626953125,
 -0.0284881591796875,
 0.047821044921875,
 0.005207061767578125,
 0.039886474609375,
 -0.050689697265625,
 -0.0193939208984375,
 -0.034423828125,
 -0.0167236328125,
 0.005115509033203125,
 -0.0177154541015625,
 -0.01678466796875,
 0.00020313262939453125,
 0.030303955078125,
 0.03143310546875,
 -0.009246826171875,
 0.0036449432373046875,
 0.0282745361328125,
 0.00029468536376953125,
 0.009521484375,
 0.029693603515625,
 -0.0189971923828125,
 0.003177642822265625,
 -0.03704833984375,
 0.0457763671875,
 -0.0253143310546875,
 0.024932861328125,
 -0.07769775390625,
 0.0022125244140625,
 -0.028076171875,
 -0.0163421630859375,
 0.0019855499267578125,
 -0.0023403167724609375,
 0.00598907470703125,
 -0.0297088623046875,
 0.0180816650390625,
 -0.0025081634521484375,
 0.025787353515625,
 -0.0241241455078125,
 0.0166473388671875,
 -0.01776123046875,
 -0.00836944580078125,
 0.045379638671875,
 0.024566650390625,
 -0.01372528076171875,
 -0.02947998046875,
 0.02264404296875,
 -0.021820068359375,
 -0.01055145263671875,
 -0.02398681640625,
 -0.023101806640625,
 -0.014434814453125,
 0.0189208984375,
 -0.03106689453125,
 -0.03826904296875,
 0.012054443359375,
 0.054107666015625,
 0.0124664306640625,
 -0.012847900390625,
 0.0089263916015625,
 0.013275146484375,
 0.027862548828125,
 0.034454345703125,
 0.0023441314697265625,
 -0.031402587890625,
 -0.038787841796875,
 -0.020599365234375,
 -0.059814453125,
 -0.00122833251953125,
 0.01198577880859375,
 0.020416259765625,
 -0.00429534912109375,
 0.0143280029296875,
 -0.0239105224609375,
 0.041656494140625,
 0.041534423828125,
 -0.024017333984375,
 -0.006229400634765625,
 0.0191192626953125,
 0.0121002197265625,
 -0.0221710205078125,
 0.01241302490234375,
 0.0091094970703125,
 -0.0271148681640625,
 0.03753662109375,
 -0.018310546875,
 0.043487548828125,
 0.0182647705078125,
 0.0228271484375,
 0.035919189453125,
 -0.01290130615234375,
 -0.0168609619140625,
 -0.0300445556640625,
 -0.0119781494140625,
 -0.03643798828125,
 -0.0188751220703125,
 -0.038299560546875,
 -0.01287841796875,
 0.018218994140625,
 -0.0198211669921875,
 -0.0010347366333007812,
 0.00390625,
 0.0168304443359375,
 -0.016082763671875,
 -0.00778961181640625,
 -0.01291656494140625,
 -0.03570556640625,
 0.019287109375,
 0.00493621826171875,
 0.0263519287109375,
 0.033660888671875,
 -0.00026869773864746094,
 -0.020751953125,
 -0.04705810546875,
 -0.00864410400390625,
 0.0019550323486328125,
 -0.0029811859130859375,
 -0.00799560546875,
 -0.00562286376953125,
 -0.035736083984375,
 0.0266876220703125,
 -0.0280914306640625,
 0.007450103759765625,
 0.024810791015625,
 0.010345458984375,
 -0.019866943359375,
 0.0202178955078125,
 0.0033283233642578125,
 -0.00937652587890625,
 -0.02117919921875,
 0.0206756591796875,
 0.0180511474609375,
 -0.004024505615234375,
 -0.002483367919921875,
 -0.028839111328125,
 -0.008453369140625,
 -0.00646209716796875,
 -0.008270263671875,
 -0.01313018798828125,
 -0.005985260009765625,
 -0.01053619384765625,
 0.007671356201171875,
 0.0021610260009765625,
 -0.01093292236328125,
 0.01126861572265625,
 -0.043182373046875,
 0.013641357421875,
 0.022003173828125,
 0.04803466796875,
 0.048309326171875,
 -0.01541900634765625,
 -0.03680419921875,
 -0.0021686553955078125,
 0.0265350341796875,
 0.019775390625,
 0.0003764629364013672,
 0.014007568359375,
 -0.040771484375,
 0.01403045654296875,
 -0.03509521484375,
 -0.0129547119140625,
 -0.02618408203125,
 0.005138397216796875,
 0.05328369140625,
 0.0093536376953125,
 -0.01140594482421875,
 -0.015594482421875,
 -0.033538818359375,
 0.0225830078125,
 -0.0096435546875,
 0.0300750732421875,
 0.003520965576171875,
 0.0160675048828125,
 0.029815673828125,
 -0.00934600830078125,
 -0.01099395751953125,
 -0.01727294921875,
 7.534027099609375e-05,
 -0.01177215576171875,
 0.0072021484375,
 0.017791748046875,
 -0.02471923828125,
 0.0017385482788085938,
 -0.003772735595703125,
 -0.027862548828125,
 0.018280029296875,
 0.026031494140625,
 -0.01091766357421875,
 -0.040557861328125,
 0.037750244140625,
 0.0311279296875,
 9.292364120483398e-05,
 0.0037689208984375,
 -0.047119140625,
 0.021392822265625,
 -0.0165863037109375,
 0.025604248046875,
 0.023468017578125,
 0.0120697021484375,
 -0.0033779144287109375,
 -0.025787353515625,
 -0.044189453125,
 0.0267181396484375,
 0.041595458984375,
 0.0155792236328125,
 0.0161285400390625,
 -0.00882720947265625,
 -0.0034503936767578125,
 0.040679931640625,
 9.542703628540039e-05,
 -0.002109527587890625,
 -0.002567291259765625,
 0.0295257568359375,
 0.0016527175903320312,
 0.01132965087890625,
 0.0118865966796875,
 -0.0282135009765625,
 0.0289459228515625,
 0.0088958740234375,
 -0.040985107421875,
 0.01367950439453125,
 -0.035003662109375,
 -0.0079803466796875,
 0.0035572052001953125,
 -0.0215301513671875,
 0.00946807861328125,
 -0.014862060546875,
 -0.000545501708984375,
 -0.0266265869140625,
 -0.0309600830078125,
 -0.01531219482421875,
 -0.00565338134765625,
 0.0085906982421875,
 0.01140594482421875,
 0.0308074951171875,
 -0.0057525634765625,
 -0.001689910888671875,
 -0.036224365234375,
 -0.0036754608154296875,
 -0.029449462890625,
 0.0092620849609375,
 -0.012664794921875,
 -0.01386260986328125,
 0.01459503173828125,
 -0.0226898193359375,
 0.0088958740234375,
 0.01360321044921875,
 0.00092315673828125,
 0.001003265380859375,
 -0.01971435546875,
 -0.00428009033203125,
 0.0184783935546875,
 -0.038421630859375,
 -0.00946807861328125,
 -0.01175689697265625,
 0.0291900634765625,
 0.0078582763671875,
 0.031036376953125,
 -0.0238494873046875,
 0.006809234619140625,
 -0.00823211669921875,
 0.014862060546875,
 0.0255889892578125,
 0.0013179779052734375,
 0.0244598388671875,
 0.01702880859375,
 -0.0175933837890625,
 0.008056640625,
 -0.01183319091796875,
 -0.01702880859375,
 0.0274200439453125,
 0.0172271728515625,
 0.01934814453125,
 0.04791259765625,

#### Crete Qdrant collection(http://localhost:6333/dashboard#/collections)

In [26]:
qdrant_client = QdrantClient(url="http://localhost:6333")

/var/folders/r_/3061nb0s7px95mfb__nvwjsc0000gn/T/ipykernel_65449/3504550968.py:1: UserWarning: Qdrant client version 1.16.1 is incompatible with server version 1.18.0. Major versions should match and minor version difference must not exceed 1. Set check_compatibility=False to skip version check.
  qdrant_client = QdrantClient(url="http://localhost:6333")

In [27]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-00",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE)
)

True

## Embed Data

##### Test

In [ ]:
text = "Test text"

pointstruct = PointStruct(
    id=0,
    vector=get_embedding(text),
    payload={
        "text": text,
        "model": "text-embedding-3-small"
    }
)

### Amazon data

In [30]:
pointstructs = []
for i, data in enumerate(data_to_embed):
    embedding = get_embedding(data["description"])
     
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload=data
        )
    )

In [ ]:
len(pointstructs)

### Write embedded data to Qudrant

In [35]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-00",
    wait=True,
    points=pointstructs
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

#### Define a function for data retrieval

In [37]:
def retrieve_data(query, k=5):
    query_embedding = get_embedding(query)
    results = qdrant_client.query_points(
        collection_name = "Amazon-items-collection-00",
        query = query_embedding,
        limit = k
    )

    return results

### test retrieval

In [43]:
retrieve_data("What best classic music do you offer?", k=10).points

[ScoredPoint(id=31, version=1, score=0.45995027, payload={'description': 'Complete Classic Rock Collection 8 CD Box ', 'image': 'https://m.media-amazon.com/images/I/316zP7tHdvL.jpg', 'rating_number': 644, 'price': None, 'average_rating': 4.4, 'parent_asin': 'B004NW4BL0'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1, version=1, score=0.39301017, payload={'description': '5 Classic Albums ', 'image': 'https://m.media-amazon.com/images/I/51dpJ3j1kWL.jpg', 'rating_number': 642, 'price': None, 'average_rating': 4.7, 'parent_asin': 'B07DMPR78Q'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=27, version=1, score=0.27918833, payload={'description': 'BEE GEES ODESSA MINI LP CD OBI ', 'image': 'https://m.media-amazon.com/images/I/41MIPtAc5ML.jpg', 'rating_number': 287, 'price': None, 'average_rating': 4.6, 'parent_asin': 'B00NF15R2W'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=16, version=1, score=0.27638134, payload={'description': "Handel's Messiah: A Soulful Celebration by unknown (1992) Audio CD ", 'image': 'https://m.media-amazon.com/images/I/61v8QyChPOL.jpg', 'rating_number': 455, 'price': 48.98, 'average_rating': 4.8, 'parent_asin': 'B00G2J0CH4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=37, version=1, score=0.2676574, payload={'description': 'Bon Jovi - Gonna Set The World On Fire: The Legendary Broadcasts 1983-1993 [4 CD Set] ', 'image': 'https://m.media-amazon.com/images/I/51SYCzL6-SL.jpg', 'rating_number': 125, 'price': 18.4, 'average_rating': 4.4, 'parent_asin': 'B01MTD4SZ7'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=45, version=1, score=0.26478958, payload={'description': 'Strangers in the Night by Sinatra, Frank (1990) Audio CD ', 'image': 'https://m.media-amazon.com/images/I/51Y9u+4-nhL.jpg', 'rating_number': 287, 'price': 24.99, 'average_rating': 4.8, 'parent_asin': 'B00GG3SOJE'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=12, version=1, score=0.26448032, payload={'description': '90125 (expanded & remastered) ', 'image': 'https://m.media-amazon.com/images/I/21RAAXGZHCL.jpg', 'rating_number': 1333, 'price': 28.61, 'average_rating': 4.7, 'parent_asin': 'B000228V66'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3, version=1, score=0.26409853, payload={'description': 'Elvis Presley - He Touched Me The Gospel Music - 3pc set ', 'image': 'https://m.media-amazon.com/images/I/5149Y9AH32L.jpg', 'rating_number': 749, 'price': 14.71, 'average_rating': 4.7, 'parent_asin': '5559166928'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=1, score=0.25344336, payload={'description': 'Enrique Iglesias- Sex and Love Deluxe Extended Edition with 4 Bonus Tracks ', 'image': 'https://m.media-amazon.com/images/I/51grTONtjpL.jpg', 'rating_number': 742, 'price': 2.99, 'average_rating': 4.6, 'parent_asin': 'B00J3J3KNI'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=34, version=1, score=0.24963246, payload={'description': 'Once Historias Y un Piano ', 'image': 'https://m.media-amazon.com/images/I/51hpZ+FapIL.jpg', 'rating_number': 213, 'price': 17.7, 'average_rating': 4.7, 'parent_asin': 'B00GMMOEZW'}, vector=None, shard_key=None, order_value=None)]